site_name: Tenis de Mesa - Liga Dos Orillas

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Cambiar a modo oscuro 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Cambiar a modo claro
  language: es
  icon:
    logo: material/table-tennis
  favicon: assets/images/favicon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.tabs.link

markdown_extensions:
  - meta
  - tables
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: 'snippets'

extra:
  analytics:
    provider: google
    property: G-268156801

copyright: Tenis de Mesa - Liga Dos Orillas 2017 - 2022 &copy; Sebastián Vanrell

repo_url: https://github.com/srvanrell/ranking-table-tennis
repo_name: srvanrell/ranking-table-tennis
edit_uri: ""

plugins:
  - search
  - macros

nav:
    - Inicio: index.md
    - Campeonato: season/2022/championship.md
    - Nivel de Juego / Categorías: season/2022/rating.md
    - season/2022/matches.md
    - season/2022/historical.md
    - season/2022/statistics.md
    - season/2022/regulation.md
    - Temporadas anteriores: season