name: test-if-workflow
on: workflow_dispatch
permissions:
  contents: write
jobs:
  somejob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
    #   - id: step-out
    #     run: echo "stop_workflow=true" >> "$GITHUB_OUTPUT"
      - id: step-out
        run: python testsetenv.py
      - if: ${{ steps.step-out.outputs.stop_workflow != 'true' }}
        run: echo "message that should be skipped"